version: "3"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq_data:/data

  database:
    build: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata

  user_api:
    build: user_service/user_backend
    links:
      - database
      - rabbitmq
    restart: on-failure
    ports:
      - "1234:1234"
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
      DB: users
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entry_point.sh"

  book_api:
    build: book_service/book_backend
    links:
      - database
      - rabbitmq
    restart: on-failure
    ports:
      - "1235:1235"
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
      DB: books
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entry_point.sh"

  issue_api:
    build: issue_service/issue_backend
    links:
      - database
      - rabbitmq
    restart: on-failure
    ports:
      - "1233:1233"
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: issues
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entry_point.sh"

  nginx:
    image: nginx:1.19.0-alpine
    depends_on:
      - book_api
      - user_api
      - issue_api
    ports:
      - "1212:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  rabbitmq_data: