name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run docker-compose without tests
        run: components/docker-compose up -d

      - name: Run books_api tests
        run: components/docker-compose run books_api python3 -m py.test -v
