name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run docker-compose without tests
        run: docker-compose -f components/docker-compose.yml build

      - name: Run books_api tests
        run: cd components/ && docker-compose run book_api python3 -m py.test -v tests

      - name: Run user_api tests
        run: cd components/ && docker-compose run user_api python3 -m py.test -v tests

      - name: Run issue_api tests
        run: cd components/ && docker-compose run issue_api python3 -m py.test -v tests
